
#Budapest időjárásának lekérdezése
#GET https://api.darksky.net/forecast/2f4659626fb968a85a5ff22561962711/47.49801,19.03991

#a fölösleges adatok kizárásával:
# exlude=minutely,hourly,alerts,flags

#így marad a 
# currently,daily

#szükséges még a nyelv beállítása az összefoglalóhoz
# lang=

#és a units=auto a városnak megfelelő mértékegységet használja.

GET https://api.darksky.net/forecast/2f4659626fb968a85a5ff22561962711/47.49801,19.03991?exclude=minutely,hourly,alerts,flags&units=si&lang=hu
Accept-Encoding: gzip